services:
  a11y-database:
    image: postgres
    container_name: a11y-database
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGUSER=${DATABASE_USERNAME}
    volumes:
      - .././postgres:/var/lib/postgresql/data/pgdata
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "psql -l | grep ${DATABASE_NAME} | wc -l | grep 1"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
